### ISSUE TITLE
レビュー反映

### ISSUE THREAD

**Issue by syucream** [syucream/mrubook#24]

**Comment by syucream** [comment]
初稿です :) [mrubook.pdf](https://github.com/syucream/mrubook/files/853213/mrubook.pdf)
レビュー結果は pdf による直赤入れ、あるいは原稿への直接 pullreq の形でいただけると嬉しいです

**Comment by take-cheeze** [comment]
@syucream ちょっとPR送りました。

**Comment by portown** [comment]
@syucream 一度通して読みました。
Acrobat Readerでコメント付けたけどちゃんと見えなかったらゴメンナサイ。。
[mrubook_portown01.pdf](https://github.com/syucream/mrubook/files/868242/mrubook_portown01.pdf)

**Comment by syucream** [comment]
@take-cheeze PR ありがとうございました！

@portown レビューありがとうございます！手元でコメント読めることが確認できました！順次反映していこうと思います〜

**Comment by syucream** [comment]
https://github.com/syucream/mrubook/commit/13f7dc65ccdcfe8de3f481ec83c20c13bc9b331b で頂いたレビューを反映しました :)
